    
---
- hosts: localhost
  become: yes
  tasks:
  - name: add repo
    apt_repository: 
      repo: ppa:openjdk-r/ppa    
  - name: install openjdk-8
    apt:
      name: openjdk-8-jdk
      update_cache: yes
      state: present 
  - name: Ensure group "tomcat" exists
    group:
      name: tomcat 
      state: present 
  - name: Add the user 'tomcat' with a specific uid and a primary group of 'tomcat'
    user:
      name: tomcat 
      comment: tomcat done
      group: tomcat
  - name: create folder
    file:
      path: /home/ubuntu/tomcat
      state: directory
      mode: 0755
      owner: ubuntu
      group: ubuntu
  - name: Download tomcat
    get_url: url=https://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.40/bin/apache-tomcat-8.5.40.tar.gz dest=/home/ubuntu/tomcat
  - name: Extract archive
    unarchive: src=/home/ubuntu/tomcat/apache-tomcat-8.5.40.tar.gz dest=/home/ubuntu/tomcat
  - name: start apache-tomcat-8.5.40
    shell: /home/ubuntu/tomcat/apache-tomcat-8.5.40/bin/startup.sh
  - name: copy gameoflife.war
    shell: cp /home/ubuntu/ansible_terraform_deployment/gameoflife.war /home/ubuntu/tomcat/apache-tomcat-8.5.40/webapps/
  handlers:
    - name: tomcat-8-restart
      service: 
        name: tomcat 
        state: restarted